Repository Amit366/FunwithPhysics, pull requests merged in 2021-07, with the labels that each got.

#11 Homepage added
  funwithpysics/package-lock.json
  funwithpysics/package.json
  funwithpysics/public/index.html
  funwithpysics/src/App.css
  funwithpysics/src/App.js
  funwithpysics/src/Components/Footer/Footer.js
  funwithpysics/src/Components/Home/Home.css
  funwithpysics/src/Components/Home/Home.js
  funwithpysics/src/Components/Navbar/Navbar.js
  funwithpysics/src/Images/bg1.jpg
  funwithpysics/src/index.css
  funwithpysics/src/index.js
Labels: DevIncept

#19 Added Images to Physics Content
  funwithpysics/src/Components/Home/Home.css
  funwithpysics/src/Components/Home/Home.js
  funwithpysics/src/Images/Classical_Mechanics.jpg
  funwithpysics/src/Images/Thermodynamics.jpg
  funwithpysics/src/Images/atomic_physics.jpg
  funwithpysics/src/Images/electromagnetism.jpg
  funwithpysics/src/Images/nuclear.jpg
  funwithpysics/src/Images/photonics.jpg
  funwithpysics/src/Images/relativity.jpg
  funwithpysics/src/Images/statistical.jpg
Labels: DevIncept

#26 Added Footer Section
  funwithpysics/src/Components/Footer/Footer.css
  funwithpysics/src/Components/Footer/Footer.js
Labels: DCP21, 🟨 Level2

#36 CONTRIBUTION
  CONTRIBUTION.md
Labels: DCP21, 🟨 Level2

#37 Update README.md
  README.md
Labels: DCP21, 🟪 Level0

#33 Responsive Design
  funwithphysics/package-lock.json
  funwithphysics/src/Components/Footer/Footer.css
  funwithphysics/src/Components/Footer/Footer.js
  funwithphysics/src/Components/Home/Home.css
  funwithphysics/src/Components/Home/Home.js
  funwithphysics/src/Components/Navbar/Navbar.css
  funwithphysics/src/Components/Navbar/Navbar.js
  funwithphysics/yarn.lock
  funwithpysics/src/Components/Footer/Footer.css
  funwithpysics/src/Components/Home/Home.css
  funwithpysics/src/Components/Navbar/Navbar.css
  package-lock.json
Labels: DCP21, 🟨 Level2
